version: '3.8'

services:
  plasma-wallet-tracker-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: plasma-wallet-tracker-dev
    restart: "no"
    env_file:
      - .env
    environment:
      # Override for development
      REDIS_HOST: redis-dev
      LOG_LEVEL: debug
      LOG_FORMAT: console
      SERVICE_COMMAND_CHANNEL: wallet_commands_dev
      SERVICE_NOTIFICATION_CHANNEL: wallet_notifications_dev
    depends_on:
      - redis-dev
    networks:
      - plasma-dev-network
    volumes:
      - .:/app
      - go_mod_cache:/go/pkg/mod
    working_dir: /app
    command: go run ./cmd/plasma-wallet-tracker
    ports:
      - "8080:8080"

  redis-dev:
    image: redis:7-alpine
    container_name: plasma-redis-dev
    restart: "no"
    command: redis-server --appendonly yes --appendfsync no
    ports:
      - "6380:6379"
    volumes:
      - redis_dev_data:/data
    networks:
      - plasma-dev-network

volumes:
  redis_dev_data:
    driver: local
  go_mod_cache:
    driver: local

networks:
  plasma-dev-network:
    driver: bridge
